# Generated by Django 4.1.5 on 2023-06-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('tracking_id', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=100)),
                ('height', models.DecimalField(decimal_places=2, max_digits=100)),
                ('delivery_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Packaging', 'Packaging'), ('In Transit', 'In Transit'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered')], max_length=255)),
            ],
        ),
    ]
