# Generated by Django 5.1 on 2025-02-22 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('senderName', models.CharField(default='', max_length=255)),
                ('senderEmail', models.CharField(default='', max_length=255)),
                ('senderPhone', models.CharField(default='', max_length=255)),
                ('senderAddress', models.CharField(default='', max_length=255)),
                ('recipeintName', models.CharField(default='', max_length=255)),
                ('recipeintPhone', models.CharField(default='', max_length=255)),
                ('recipeintAddress', models.CharField(default='', max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('tracking_id', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('height', models.DecimalField(decimal_places=2, max_digits=20)),
                ('coupon', models.CharField(default='', max_length=15)),
                ('delivery_location', models.CharField(max_length=255)),
                ('additionalComment', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Packaging', 'Packaging'), ('In Transit', 'In Transit'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered')], default='Processing', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
