# Generated by Django 5.1 on 2025-02-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='additionalComment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_id',
            field=models.CharField(max_length=255),
        ),
    ]
