# Generated by Django 4.1.5 on 2023-06-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='name',
        ),
        migrations.AddField(
            model_name='package',
            name='additionalComment',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='package',
            name='recipeintAddress',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='recipeintName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='recipeintPhone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='senderAddress',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='senderEmail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='senderName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='senderPhone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='package',
            name='product',
            field=models.CharField(default='', max_length=255),
        ),
    ]
