# Generated by Django 4.1.5 on 2023-06-27 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_package_name_package_additionalcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Packaging', 'Packaging'), ('In Transit', 'In Transit'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered')], default='Processing', max_length=255),
        ),
    ]
