# Generated by Django 4.1.5 on 2023-06-27 08:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_package_created_at_alter_package_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
