# Generated by Django 4.1.5 on 2023-06-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='coupon',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='package',
            name='additionalComment',
            field=models.CharField(max_length=1000),
        ),
    ]
